<!DOCTYPE html
  PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html lang="en-us" xml:lang="en-us"> 
<head> 

<link rel="stylesheet" type="text/css" href="help.css"/> 
<link rel="stylesheet" type="text/css" href="/sCSS/Theme2/default/help.css"/> 
<title>Creating Cases</title> 
<script type="text/javascript" language="JavaScript" src="/js/functions.js"> </script> 
</head> 
<body onLoad="highlightToc(&#34;Cases&#34;, &#34;cases_create&#34;);" id="cases_create"><a name="cases_create"><!-- --></a> 
 
<a name="top"><!-- --></a> 
 
 
<h1 class="helpHead1"><a name="d11820e15"><!-- --></a><span id="topic-title"><a name="topic-title"><!-- --></a>Creating Cases</span></h1> 
 
 
<div> 
 
<br/> 
 
 
<table class="permTable" cellpadding="0" cellspacing="0" summary="Permissions needed for the documented functionality" width="100%" border="0"> 
<thead align="left"> 
<tr> 
<th class="permTableHeader" colspan="2" id="d11820e79">User Permissions
Needed</th> 
 
</tr> 
 
</thead> 
 
<tbody> 
<tr> 
<td class="permRowLeft" headers="d11820e79 ">To view cases:</td> 
 
<td class="permRowRight" headers="d11820e79 ">"Read" on cases</td> 
 
</tr> 
 
<tr> 
<td class="permRowLeft" headers="d11820e79 ">To create cases:</td> 
 
<td class="permRowRight" headers="d11820e79 ">"Create" on cases</td> 
 
</tr> 
 
</tbody> 
 
</table> 
 
<div class="p"> 
You can create cases in various ways:<ul> 
<li>Your administrator can set up Web-to-Case and either Email-to-Case
or <span>On-Demand Email-to-Case</span> to automatically
capture cases from your website and customer emails (see <a href="customize_casecapture.htm"><span>Capturing Web Cases</span></a> and <a href="customizesupport_email.htm"><span>Setting Up Email-to-Case or <span>On-Demand Email-to-Case</span></span></a>)</li> 
 
<li>Your customers can log their own cases from the <span>Self-Service</span> portal
or <span>Customer Portal</span></li> 
 
<li>You can create cases manually in the Cases tab</li> 
 
</ul> 
</div> 
 
<p> 
To create a new case :</p> 
 
<ol> 

<li>Click the <strong>Account</strong> lookup icon. Initially,the Account lookup lists all Accounts 
Enter search criteria and click <strong>Go!</strong> to refine this list.</li> 
 

<li>To associate the new asset with a product, enter your product
search criteria and click <strong>Go!</strong> or select a product
from the list of matches. Click <strong>Skip</strong> if you
do not want to associate the asset with a product.</li> 
 
<li>To associate the case with an asset: Click the <strong>Asset</strong> lookup icon. Initially,
the asset lookup lists all assets. It lists all assets for the account and product if both are selected.
<li>The asset lookup lists all assets for the Account if one is selected. Enter search criteria and click <strong>Go!</strong> to refine this list.</li> 
<li>when selecting  the asset from lookup window,account and product is automatically populated. Select an asset from the assets listed to associate it with the
case.</li> 


 
</ol> 
</li> 
 

<li>Click <strong>Save</strong> to save the case.
</li> 
 
</ol> 


</div> 

                      
                   
</body> 
</html>