public with sharing class acpcls {

    public PageReference sanjeevareddy() {
        name='sajayy';
        return null;
    }


    public PageReference motaaaa() {
        name='motaramrao';
        return null;
    }


    public PageReference rafi() {
        name='rafireddy';
        return null;
        
    }


    public PageReference unchangename() {
        name='helloshajuuu';
        return null;
    }


    public String name { get; set; }

    public PageReference changename() {
    
        name='hello mikelllll';
        return null;
    }
    public acpcls(){
        name='hello surendra';
        }
}