public class BankAccountTest{
    public static testMethod void banking(){
        
       /* BankAccount.getCount(new BankAccount());
        
        BankAccount atm=new BankAccount();
       // atm.setValues(20000,'surendra',313371994,'MARKAPUR');
        BankAccount.getCount(new BankAccount());
        atm.setValues(30000,'surendra',313371994,'MARKAPUR');
        atm.withdrawBalence(36007);
        atm.depositBalence(10000);
        atm.checkBal();
        atm.getValues();*/
        
        
       /* BankAccount atm1=new BankAccount();
        
        atm1.setValues(10000,'shaju',313371995,'MARKAPUR');
        atm1.withdrawBalence(5000);
        atm1.depositBalence(10000);
        atm1.checkBal();
       // BankAccount.getCount();
        
        BankAccount atm2=new BankAccount();
        atm2.setValues(30000,'mikel',313371996,'MARKAPUR');
        atm2.withdrawBalence(5000);
        atm2.depositBalence(10000);
        atm2.checkBal();
       // BankAccount.getCount();
        
        BankAccount atm3=new BankAccount();
        atm3.setValues(40000,'rafireddy',313371994,'MARKAPUR');
        atm3.withdrawBalence(5000);
        atm3.depositBalence(10000);
        atm3.checkBal();
       // BankAccount.getCount();*/
       //atm.getValues();
      /* SavingAccount sa=new SavingAccount();
       sa.intrest(4,10);
       sa.getValues();*/
       
       BankAccount atm=new BankAccount();
        atm.setValues(30000,'surendra',313371994,'MARKAPUR');
        atm.withdrawBalence(36007);
        atm.getValues();
     }
}