public class substraction {
    
    public integer value1{set;get;}
     public integer value2{set;get;}
     //public integer res1{set;get;}
    // public integer res2{set;get;}
     public integer res3{set;get;}
     //public integer value3{set;get;}
    
    
    public substraction(demo12 controller) {

    }

     public void sub() {
        
        res3=value1-value2-2;
       
    } 
    
}