public class TestRectangle{
     public static testMethod void testRectangle(){
          Rectangle bat=new Rectangle(10,5);
              bat.getValues();
              bat.setValues(4,2);
              bat.setValues(5,2);
              integer area=bat.area();
              integer perm=bat.perimeter();
              System.debug('area ia :'+area);
              System.debug('area ia :'+perm);
              bat.getValues();
              }
              
        /*  Rectangle slate=new Rectangle(20,5);
              slate.getValues();
              slate.setValues(6,2);
              slate.getValues();
          
          Rectangle mat=new Rectangle(30,5);
              mat.getValues();
              mat.setValues(8,2);
              mat.getValues();
          Point p1=new Point();
              p1.setValues(3,4);
              p1.getValues();*/
              
        
          }