<script type="text/javascript">
       
        function show(){
           var vname=document.getElementById('p1:p2:p3:p4').value
           if(vname==''){
               alert(' u must type uname');
               }
            }
         
        function hide(){
            document.getElementById('p1:p2:p3:p4').style.display='none';
            alert('hi');
            }                           
</script>